- name: deploy reminder 
  hosts: test_host
  gather_facts: False
  #  become: true

  tasks:

    - name: deploy
      copy:
        src: ~/ansible/reminder.py
        dest: /home/greenbec/
        mode: 0644 

    - name: deploy
      copy:
        src: ~/ansible/reminder_utils.py
        dest: /home/greenbec/
        mode: 0644

